group-4-capstone/iAdopt

- src/components/footer.php
- src/components/topnavbar.php
- src/home.php
- src/styles/footer.css
- src/styles/styles.css
- src/styles/topnavbar.css
> feat: add components

- src/add-record.php
- src/rescue-records.php
- src/styles/add-record.css
- src/styles/rescue-records.css
Overview
Responsive UI for the content of the page add record page
WIP
- paw prints still not in this commit
- responsive header and picture
> Added ui for add-record page

- src/home.php
- src/styles/footer.css
- src/styles/shop.css
- src/styles/topnavbar.css
- src/visit-us.php
> style: adjust css styles for better responsiveness and others

- src/includes/db-connect.php
iadopt sql
[iadopt sql.txt](https://github.com/user-attachments/files/17135829/iadopt.sql.txt)
on-going report stray backend
@AraojoBenedict
> feat: create connection to db

- src/includes/submit-rescue.php
- src/includes/submit-visit.php
- src/report-stray.php
- src/scripts/report-stray.js
- src/scripts/visit-us.js
- src/styles/adopt.css
- src/styles/report.css
- src/styles/visit.css
- src/visit-us.php
no user_id inserted, will update when login feature and session are implemented
@AraojoBenedict
> feat: initial backend on visit form

- src/adopt-now.php
- src/includes/submit-rescue.php
- src/includes/submit-visit.php
- src/report-stray.php
- src/scripts/adopt-now.js
- src/scripts/form.js
- src/scripts/report-stray.js
- src/scripts/visit-us.js
- src/styles/report.css
- src/styles/visit.css
- src/visit-us.php
> validation visit and report form

- src/includes/submit-liquidation.php
- src/liquidation-monitoring.php
- src/scripts/liquidation.js
- src/styles/liquidation.css
> feat: list donation and expenses with validations

- src/liquidation-monitoring.php
> GR4-142 feat: display dynamic info in liquidation monitoring

- src/includes/signup-process.php
- src/scripts/signup.js
- src/signup.php
I Advise merge first this pr before testing because for whatever reason this branch doesnt have the db-connect.php in the includes directory.
> GR4-129 Signup backend

- src/rescue-records.php
- src/scripts/rescue-records.js
- src/styles/rescue-records.css
updated rescue records added table for rescue request
> updated rescue records added table for rescue request

- src/includes/submit-visit.php
- src/scripts/visit-us.js
- src/styles/visit.css
- src/visit-us.php
> fix: add date and time input fields in visit with validation

- src/includes/fetch-visit.php
- src/styles/visitor-log.css
- src/visitor-log.php
> GR4-146 chore: use ajax in displaying data in table and pagination

- src/includes/fetch-liquidation.php
- src/liquidation-monitoring.php
- src/styles/liquidation.css
- src/visitor-log.php
> GR4-142 chore: display data using ajax and pagination

- src/includes/submit-visit.php
- src/scripts/visit-us.js
- src/styles/visitor-log.css
- src/visitor-log.php
> GR4-144 feat: add visit function in admin side

- src/adopt-now.php
- src/content-management.php
- src/includes/submit-announcement.php
- src/scripts/content-management.js
- src/styles/content-management.css
- src/styles/styles.css
> feat: add back-end announcement

- src/includes/login-process.php
- src/login.php
modify the the password column in the users table in testing this pr
> Initial login back end

- src/animal-record.php
- src/includes/fetch-liquidation.php
- src/includes/fetch-records.php
- src/includes/fetch-reports.php
- src/includes/fetch-visit.php
- src/includes/submit-record.php
- src/includes/submit-rescue.php
- src/liquidation-monitoring.php
- src/report-stray.php
- src/rescue-records.php
- src/scripts/rescue-records.js
- src/styles/styles.css
- src/visitor-log.php
TO FOLLOW UPDATING THE STATUS WHEN ACCEPT IS CLICKED, THE DATA SHOULD BE MOVED INTO THE RESCUE TABLE IF ACCEPTED
> Gr4 155 rescue records

- src/styles/account-management.css
- src/styles/add-record.css
- src/styles/adoption-records.css
- src/styles/animal-profiles.css
- src/styles/content-management.css
- src/styles/history.css
- src/styles/liquidation.css
- src/styles/rescue-records.css
- src/styles/styles.css
- src/styles/visitor-log.css
> GR4-159- adjust-css

- src/add-record.php
- src/animal-record.php
- src/components/sidebar.php
- src/content-management.php
- src/includes/fetch-announcements.php
- src/includes/fetch-faqs.php
- src/includes/fetch-merchandise.php
- src/includes/fetch-volunteers.php
- src/liquidation-monitoring.php
- src/scripts/animal-profile.js
- src/scripts/content-management.js
- src/scripts/liquidation.js
- src/scripts/rescue-records.js
- src/styles/add-record.css
- src/styles/content-management.css
- src/styles/rescue-records.css
- src/styles/styles.css
> Gr4 160 gr4 161 gr4 162 gr4 163 gr4 164 changes

- src/content-management.php
- src/includes/login-process.php
- src/includes/submit-announcement.php
- src/includes/submit-application.php
- src/includes/submit-faq.php
- src/includes/submit-liquidation.php
- src/includes/submit-merch.php
- src/includes/submit-rescue.php
- src/includes/submit-volunteer.php
- src/scripts/content-management.js
- src/scripts/modal-tab.js
soon edit details/post
will be merging this now @AraojoBenedict
> Gr4 164 display modals

- src/content-management.php
- src/includes/edit-announcement.php
- src/includes/edit-faq.php
- src/includes/edit-merchandise.php
- src/includes/edit-volunteer.php
- src/scripts/content-management.js
- src/scripts/modal-tab.js
> GR4-165 feat: edit feature in modals of content management tables

- src/components/sidebar.php
- src/includes/login-process.php
- src/includes/session-manager.php
> Sidebar update

- src/adoption-details.php
- src/adoption-records.php
- src/includes/fetch-adoption-applications.php
- src/scripts/adoption-records.js
- src/styles/adoption-records.css
> Gr4 176 gr4 177 adoption records

- src/includes/update-status.php
- src/rescue-records.php
- src/scripts/rescue-records.js
when accept button is clicked
click yes
> GR4-179- feat update status of report from waitlist to under review

- src/animal-record.php
- src/includes/edit-record.php
- src/rescue-records.php
- src/scripts/animal-profile.js
- src/scripts/rescue-records.js
> GR4-179 GR4-181 feat: update status and other edit fixes

- src/account-management.php
- src/includes/add-acc.php
- src/includes/fetch-users.php
- src/includes/update-accstatus.php
- src/scripts/account-management.js
- Issues to Improve:
- Still doesnt have the emailer when adding account.
> feat: GR4-184 Initial Back-end of Account-Management

- src/components/topnavbar.php
> GR4-191 feat: update top nav bar

- src/adopt-know-more.php
- src/adopt-now.php
- src/adopt.php
- src/home.php
- src/includes/fetch-records.php
- src/report-stray.php
- src/rescue-records.php
- src/scripts/home.js
- src/scripts/rescue-records.js
- src/scripts/shop.js
- src/shop.php
- src/styles/styles.css
- src/visit-us.php
dynamic adoption page not yet included
> GR4-194 feat: dynamic user side except for animal profiles/ adopt page

- src/account-management.php
- src/add-record.php
- src/admin-faqs.php
- src/adopt-know-more.php
- src/adopt-now.php
- src/adopt.php
- src/adopter-faqs.php
- src/adoption-details.php
- src/adoption-records.php
- src/animal-profiles.php
- src/animal-record.php
- src/components/sidebar.php
- src/content-management.php
- src/dashboard.php
- src/donate.php
- src/history-rest.php
- src/history.php
- src/home.php
- src/liquidation-monitoring.php
- src/report-stray.php
- src/rescue-records.php
- src/settings.php
- src/shop.php
- src/visit-us.php
- src/visitor-log.php
admin account cannot access page of user
user pages are still available to non-logged in users
users are only required to log in when adopting (adopt now) and reporting
@AraojoBenedict fyi, please correct if wrong. I will be merging this for now.
> GR4-202 fix: acces to pages acc to role

- src/adoption-details.php
- src/includes/fetch-records.php
- src/includes/update-adoption-status.php
- src/scripts/adoption-details.js
> GR4-197 feat: schedule interview function

- src/history.php
- src/includes/fetch-adopted.php
- src/includes/fetch-rest.php
- src/scripts/history.js
Search log is still not functioning well
> Initial backend history log

- src/adopt.php
- src/adopter-faqs.php
- src/animal-profiles.php
- src/content-management.php
- src/includes/submit-faq.php
- src/scripts/adopter-faqs.js
- src/styles/account-management.css
- src/styles/adopt.css
- src/styles/animal-profiles.css
> Gr4 204 faq adopter

- src/account-management.php
- src/admin-faqs.php
- src/adoption-details.php
- src/adoption-records.php
- src/animal-profiles.php
- src/animal-record.php
- src/content-management.php
- src/dashboard.php
- src/history.php
- src/includes/submit-health-info.php
- src/includes/submit-vaccine.php
- src/liquidation-monitoring.php
- src/scripts/animal-profile.js
- src/visitor-log.php
I will be merging this now just fyi. Thanks! @AraojoBenedict
> Gr4 195 medical records

- src/includes/test_mailer.php
- src/includes/test_mailer_2.php
- src/phpmailer/DSNConfigurator.php
- src/phpmailer/Exception.php
- src/phpmailer/OAuth.php
- src/phpmailer/OAuthTokenProvider.php
- src/phpmailer/PHPMailer.php
- src/phpmailer/POP3.php
- src/phpmailer/SMTP.php
kindly test @AraojoBenedict 
http://localhost/iAdopt/src/includes/test_mailer.php
> fix: phpmailer class

- src/test-semantic.php
> feat: added test-semantic.php

- .github/workflows/release.yml
added dir .github/workflows for semantic versioning
> feat: added dir .github/workflows for semantic versioning

- src/dashboard.php
- src/includes/fetch-liquidation-data.php
- src/scripts/dashboard.js
- src/styles/dashboard.css
> GR4-216 feat: initial generate liquidation reports

- src/test-semantic.php
added div to test-semantic page
> feat: added div to test-semantic page

- src/animal-record.php
- src/includes/edit-record.php
- src/includes/fetch-liquidation-data.php
- src/includes/fetch-liquidation.php
- src/includes/submit-liquidation.php
- src/includes/update-liquidation-status.php
- src/includes/update-rescue-status.php
- src/liquidation-monitoring.php
- src/scripts/animal-profile.js
- src/scripts/liquidation.js
- src/scripts/rescue-records.js
- src/styles/liquidation.css
i will be merging this fyi @AraojoBenedict thanks
> Gr4 229 liquidation

- src/add-record.php
- src/login.php
- src/scripts/rescue-records.js
- src/styles/add-record.css
- src/styles/login.css
> Gr4 244 login reponsiveness

- src/history.php
- src/includes/fetch-deny-reports.php
- src/report-stray.php
- src/rescue-records.php
- src/scripts/history.js
- src/scripts/report-stray.js
- src/styles/report.css
> GR4-240 feat: add denied reports table

- src/adoption-records.php
- src/dashboard.php
- src/history.php
- src/includes/fetch-adopted.php
- src/includes/fetch-adoption-applications.php
- src/includes/fetch-announcements.php
- src/includes/fetch-deny-reports.php
- src/includes/fetch-faqs.php
- src/includes/fetch-merchandise.php
- src/includes/fetch-records.php
- src/includes/fetch-reports.php
- src/includes/fetch-rest.php
- src/includes/fetch-visit.php
- src/includes/fetch-volunteers.php
- src/includes/submit-application.php
- src/rescue-records.php
- src/scripts/adoption-records.js
- src/scripts/history.js
- src/scripts/rescue-records.js
- src/scripts/visitor-log.js
- src/styles/dashboard.css
- src/visitor-log.php
> Gr4 246 refactor admin side

- src/adopt.php
- src/animal-record.php
- src/includes/fetch-records.php
- src/includes/fetch-reports.php
- src/rescue-records.php
- src/scripts/animal-profile.js
- src/scripts/rescue-records.js
@AraojoBenedict i will be merging this pr. just fyi. Thanks!
> Gr4 242 gr4 247 filter and sort

- src/components/sidebar.php
- src/includes/sidebar-data.php
- src/includes/update-profile.php
- src/includes/verify-password.php
- src/scripts/settings.js
- src/settings.php
- src/styles/settings.css
GR4-255
- Added Validation to the input fields of settings page.
- Dynamic Update on the sidebar
- Added Verification of Password before Changing the Password.
> Settings validation

- src/adoption-details.php
> GR4-256 feat: display post-adoption-forms
